channels:
     - conda-forge
dependencies:
     - dlib
     - numpy
     - scipy
     - opencv
     - face_recognition
     - streamlit
     - matplotlib
     - Pillow
     - tensorflow
     - keras
     - imageio
